/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limegroup_gnutella_gui_notify_WindowsNotifyUser */

#ifndef _Included_com_limegroup_gnutella_gui_notify_WindowsNotifyUser
#define _Included_com_limegroup_gnutella_gui_notify_WindowsNotifyUser
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _image */
/* Inaccessible static: _tooltip */
/*
 * Class:     com_limegroup_gnutella_gui_notify_WindowsNotifyUser
 * Method:    nativeDisable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limegroup_gnutella_gui_notify_WindowsNotifyUser_nativeDisable
  (JNIEnv *, jobject);

/*
 * Class:     com_limegroup_gnutella_gui_notify_WindowsNotifyUser
 * Method:    nativeEnable
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_limegroup_gnutella_gui_notify_WindowsNotifyUser_nativeEnable
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_limegroup_gnutella_gui_notify_WindowsNotifyUser
 * Method:    nativeFreeImage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_limegroup_gnutella_gui_notify_WindowsNotifyUser_nativeFreeImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_limegroup_gnutella_gui_notify_WindowsNotifyUser
 * Method:    nativeLoadImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_limegroup_gnutella_gui_notify_WindowsNotifyUser_nativeLoadImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_limegroup_gnutella_gui_notify_WindowsNotifyUser
 * Method:    nativeLoadImageFromResource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_limegroup_gnutella_gui_notify_WindowsNotifyUser_nativeLoadImageFromResource
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_limegroup_gnutella_gui_notify_WindowsNotifyUser
 * Method:    nativeHide
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limegroup_gnutella_gui_notify_WindowsNotifyUser_nativeHide
  (JNIEnv *, jobject);

/*
 * Class:     com_limegroup_gnutella_gui_notify_WindowsNotifyUser
 * Method:    nativeShowMenu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limegroup_gnutella_gui_notify_WindowsNotifyUser_nativeShowMenu
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
