/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limegroup_gnutella_util_WindowsLauncher */

#ifndef _Included_com_limegroup_gnutella_util_WindowsLauncher
#define _Included_com_limegroup_gnutella_util_WindowsLauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limegroup_gnutella_util_WindowsLauncher
 * Method:    nativeLaunchFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_limegroup_gnutella_util_WindowsLauncher_nativeLaunchFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_limegroup_gnutella_util_WindowsLauncher
 * Method:    nativeOpenURL
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_limegroup_gnutella_util_WindowsLauncher_nativeOpenURL
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
